Разметка
htmlacademy-htmlcss/1853291-device-32 pull request #2
Opened 2021-09-27 13:01 UTC by zazuzai

2021-09-27 14:51 UTC, katrinLuna commented
Привет, общие рекомендации до отправки ДЗ на проверку желательно:
1) проверить код в https://validator.w3.org/ и особенно обратить внимание на Ошибки типа: 
- **End tag ____ seen, but there were open elements**. - Это значит что где-то выше по коду не хватает закрывающего тега от другого открытого тега
-**Unclosed element ____** - не закрыт тег, тут чуть проще искать, потому что надо посмотреть и логически закрыть тег

2) Опубликовать проект на странице Задания и глазами проверить не поехала ли верстка или стили и прочее, то есть протестить визуально просто, в том числе на этом этапе будет видно незакрытые теги (верстка может поехать) или пустые теги (как пустой <th></th> в таблице)

2021-09-27 15:11 UTC, katrinLuna requested changes

2021-09-27 15:13 UTC, katrinLuna commented
В целом на текущей итерации ты молодец и большая часть разметки корректна. Обрати внимание и почитай ещё раз про теги `section`, `h2-h6`

2021-09-27 21:51 UTC, zazuzai commented on index.html
> +          <li role="presentation">
взяла код из статьи, которую посоветовали на дискорде при обсуждении этого блока с вкладками

2021-09-28 12:30 UTC, katrinLuna reviewed
Эта итерация кода уже выглядит более осмысленной и аккуратной, ты молодец.

Нужно доработать:
1) Форматирование (открывающий и закрывающий тег на одной вертикали, дочерние элементы сдвинуты на таб или пробелы от родительского) это важно для удобства читаемости и проверки кода
2) Нужно еще раз разобраться где и как верно использовать тег section, а где хватит. div

2021-09-28 12:30 UTC, katrinLuna commented on index.html
> +      <a href="index.html"><img src="#" class="header-logo" alt="логотип Девайс"></a>
Для удобства читаемости кода лучше на 1 строке один тег делать, в данном случае лучше вот такое форматирование по наглядности и упрощает читаемость кода:
```suggestion
      <a href="index.html">
           <img src="#" class="header-logo" alt="логотип Девайс">
      </a>
```

2021-09-28 12:30 UTC, katrinLuna commented on index.html
> +              <ul class="dropdown-catalog">
По форматированию тут до `ul` лучше добавить пустую строку, чтобы вложенность была нагляднее

2021-09-28 12:30 UTC, katrinLuna commented on index.html
> +            <a href="catalog.html">Каталог товаров</a>
Форматирование: `button` находится на одном уровне вложенности с `a`
```suggestion
 <a href="catalog.html">Каталог товаров</a>
 <button class="dropbtn"></button>
```

2021-09-28 12:30 UTC, katrinLuna commented on index.html
> +            </li>
Форматирование: закрывающий тег `li` должен быть на одном уровне с открывающим, тут и в следующих пунктах

2021-09-28 12:30 UTC, katrinLuna commented on index.html
> +        <img class="slider-image" src="#" alt="Фитнес-браслет">
Форматирование: все вложенные в section (div) теги нужно подвинуть на 1 таб или на несколько пробелов, смотря какое формативание ты используешь.

2021-09-28 12:30 UTC, katrinLuna commented on index.html
> +      <section class="slider">
Слайдер в данном случае это section, но каждый отдельный слайд может быть обернут в div. То есть тут родитель section — про весь слайдер, в том числе с пагинацией

2021-09-28 12:30 UTC, katrinLuna commented on index.html
> +        <a class="feedback" href="#">Напишите нам</a>
Поясни почему ты тут выбрала ссылку, а не кнопку?

2021-09-28 12:47 UTC, merged